로그인 컴포넌트 마크업
choco-team/FE_TeacherCan pull request #43
Opened 2023-05-20 15:42 UTC by seoltang

#40 

- [x] 로그인 컴포넌트 마크업
- [x] 로그인 컴포넌트 스토리북 추가

그 외 설정
- [x] `lightTheme`, `darkTheme`에 `theme` 포함되도록 수정
- [x] 스토리북 preview Router 추가
- [x] 이미지 파일 import 가능하도록 전역 모듈 선언
- [x] react-icons 설치

2023-05-20 18:03 UTC, nlom0218 requested changes
설탕쌤! 고생많으셨습니다! 👍

궁금한점이 있는데요! 지윤쌤도 같은 방법으로 `components` 폴더를 구성해서 제가 혹시 잘못 이해하고 있는 것이 아닐까 싶어 궁금한 점을 남겨요!

현재 `components` 폴더내의 `Login` 폴더를 만들고 해당 폴더 안에 `Login` 컴포넌트를 구성하는 컴포넌트를 다시 폴더로 나누고 이를 만든 후, 조립하였는데 그러면 Input, LinkText와 같이 Login이 아닌 다른 컴포넌트에선 재사용을 하기에 적합하지 않을까 하는 생각이듭니다.

혹시 제가 이슈를 생성할 때, `Lunch Component`와 같이 이슈를 생성했다면 죄송합니다 😭 아마 전 `Lunch Component`가 아니라 `SummaryListComponent`로 만들 예정입니다!!

이에 대해선 내일 더 이야기 해봐요~~

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/Input/index.tsx
> +  const [isPasswordVisible, setisPasswordVisible] = useState(false);
setIsPasswordVisible 🤣🤣🤣
is의 i가 소문자네요!!

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/Input/index.tsx
> +function Input({ type }: T.Input) {
Login 폴더내의 Input은 회원가입할때도 사용할 수 있을거라고 생각해요.
일반적인 Input과 다르게 AccountInput와 같이 만들고 로그인 페이지, 회원가입 페이지에서 사용할 수 있도록 하면 어떨까요?

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/Input/index.tsx
> +const INPUT_TYPE = {
상수로 관리 좋아요!

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/Input/style.ts
> +  max-width: 448px;
저는 개인적으로 최대 너비는 외부에서 주입하는 것이 좋다고 생각하는 편입니다. 여러 곳에서 재사용하는 컴포넌트인 경우엔 너비가 고정값일 수도 있고 %일수도 있기 때문이죠. 하지만 계정과 관련된 Input은 고정되어 있는 것도 괜찮을 것 같네요!

혹은 고정된 값을 기본값으로 하고 외부에서 값을 전달할 경우엔 전달받은 값으로 너비를 지정해도 괜찮을 것 같아요 👍

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/Input/style.ts
> +  padding: ${({ type }) => (type === 'email' ? '16px' : '16px 40px 16px 16px')};
오른쪽에 눈 아이콘을 위한 자리군요!

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/LinkText/index.tsx
> +  return <S.LinkText to="/">{text}</S.LinkText>;
LinkText가 여러 컴포넌트에서 사용할 수 있는 것을 고려했을 때, 이동하는 주소를 props로 전달받는 것은 어떤가요?

2023-05-20 18:03 UTC, nlom0218 commented on src/components/Login/index.tsx
전 Login 컴포넌트가 `components`가 아니라 `pages`에 있어야 한다고 생각해요. 물론 지금은 page가 없어 조립을 위해 하신것 같아 보여요. 이후에 `pages/Login/index.tsx`로 옮기실 건가요?

2023-05-20 18:03 UTC, nlom0218 commented on src/types/index.d.ts
👍

추가적으로 앞으로 asset를 불어오면 해당 asset의 타입은 아마도(...?) any일거에요. 그래서 전 다음과 같이 타입을 구체적인 타입을 지정합니다.!

```typescript
declare module '*.png' {
  const value: string;
  export default value;
}
```

2023-05-21 06:25 UTC, jjswan approved these changes
고생하셨습니다!

2023-05-21 06:25 UTC, jjswan commented on .storybook/preview.tsx
> +        <MemoryRouter initialEntries={['/']}>
Memory Router는 처음 보네요. 브라우저의 주소와 무관하며 테스트 환경에서 사용하기 좋다고 하는데 스토리북에서 테스트하기 위해서 MemoryRouter를 넣으신 것일까요? 사용해본 적이 없어서 쓰임새가 헷갈리네요.

2023-05-21 06:25 UTC, jjswan commented on src/components/Login/Input/style.ts
> +  ${flexCustom('column', 'flex-start', 'flex-start')}
flexCustom을 style.ts에서 사용하면 되는군요. 저는 이걸 type.ts에서 props로 넣는 바람에 stories.tsx까지 끌고 갔네요. 다음부터 이렇게 하면 훨씬 편할 것 같아요!

2023-05-21 06:25 UTC, jjswan commented on src/components/Login/LinkText/index.tsx
모든 컴포넌트에 stories를 만들어야 하는 것은 아닌가봐요. 저는 간단한 컴포넌트에도 다 스토리를 만들었는데... 그런데 스토리가 없으면 스토리북에서 컴포넌트를 보는 게 불가능한 것 맞나요?

2023-05-21 06:25 UTC, jjswan commented on src/components/Login/index.tsx
pages에는 공통으로 계속 사용되는 컴포넌트를 집어넣는 것일까요?

2023-05-21 06:32 UTC, nlom0218 commented on src/components/Login/index.tsx
`공통으로 계속 사용되는 컴포넌트`는 components 내에서 만들고 이를 필요한 곳에 사용할 수 있겠죠! `pages`에는 정말 그 페이지에만 필요한 컴포넌트를 만드시면 됩니담

1. 재사용할 수 있는 컴포넌트를 불러와서 사용하거나
2. 다른 페이지가 아닌 현재 페이지에서만 사용되는 컴포넌트인 경우엔 굳이 `components`가 아니라 `pages`에서 컴포넌트를 만들면 되겠죠!

2023-05-21 06:36 UTC, nlom0218 commented on src/components/Login/LinkText/index.tsx
네! 스토리가 없으면 스토리북에서 컴포넌트를 못 봐요ㅎㅎ
그리고 모든 컴포넌트를 모두 스토리북을 만들지 않아도 된다고 생각해요. 작은 단위(중요하게 생각하는)의 컴포넌트를 우선적으로 만드는 연습을 하면 좋을 것 같아요! 

이후에 페이지가 완성되면 사용자의 실제 사용을 가정하여 인터렉션 테스트를 추가하는 정도...?

2023-05-21 12:07 UTC, merged

2023-05-21 14:00 UTC, seoltang commented on .storybook/preview.tsx
> +        <MemoryRouter initialEntries={['/']}>
`Link` 컴포넌트를 넣으려고 했는데 스토리북에는 라우터가 적용이 안 돼있어서 오류가 나더라고요. 찾아보니까 저거 쓰면 된다고 하더라고요 ㅎㅎ 실제 앱이랑 무관하고 스토리북 테스트 환경에서만 쓰이는 것 맞아요!